### ISSUE TITLE
Please provide a detailed explanation of what it is, that this library is doing in the README.

### ISSUE THREAD

**Issue by aentinger** [arduino-libraries/Arduino_KNN#4]

**Comment by 8bitkick** [comment]
There is a good description in this article - https://blog.arduino.cc/2020/06/18/simple-machine-learning-with-arduino-knn/

**Comment by aentinger** [comment]
And how about you get it into the README? Also the description in [library.properties](https://github.com/arduino-libraries/Arduino_KNN/blob/master/library.properties) is far from making anything clear. As this library is hosted within the [arduino-libraries](https://github.com/arduino-libraries) github organisation I'd love to see a minimum level of beginner-friendly documentation happening.

**Comment by 8bitkick** [comment]
@aentinger I think there's a bit of confusion. I am quite busy at a new job, but when I get time I'd be happy to do this.
